# Generated by Django 5.0.4 on 2024-04-06 16:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='rand_token',
            field=models.UUIDField(default=uuid.UUID('2f879f04-c213-4184-b455-267fc71439da')),
        ),
    ]
