# Generated by Django 5.0.4 on 2024-04-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_token_rand_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='rand_token',
            field=models.UUIDField(),
        ),
    ]
